<?php

namespace Database\Factories\V2room\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\V2room\Models\Users\User>
 */
abstract class BaseFactory extends Factory
{
    /**
     * The default namespace where factories reside.
     *
     * @var string
     */
    protected static $namespace = 'Database\\Factories\\V2room\\Models\\';

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\Illuminate\Database\Eloquent\Model|TModel>
     */
    public function modelName()
    {
        $resolver = static::$modelNameResolver ?? function (self $factory) {
            $namespacedFactoryBasename = Str::replaceLast(
                'Factory', '', Str::replaceFirst(static::$namespace, '', get_class($factory))
            );

            $factoryBasename = Str::replaceLast('Factory', '', class_basename($factory));

            $appNamespace = static::appNamespace();

            return class_exists('V2room\\Models\\' . $namespacedFactoryBasename)
                ? 'V2room\\Models\\' . $namespacedFactoryBasename
                : $appNamespace . $factoryBasename;
        };

        return $this->model ?? $resolver($this);
    }
}
